language: java
java:
  - 1.8
jdk:
  - oraclejdk8

addons:
  sonarqube: true
env:
  global:
    - secure: SONAR_TOKEN=2f777ce5faa3651de36bc6ed889e637c205b1187

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle


script:
  - mvn clean install sonar:sonar -Dsonar.login=2f777ce5faa3651de36bc6ed889e637c205b1187

notifications:
  slack: codinplayproject:qHwyvthUIY8Je62ipcTtteoz
